# Generated by Django 3.1 on 2020-10-15 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friends',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='myapp/static/myapp/images/'),
        ),
    ]
