# Generated by Django 3.1 on 2020-10-29 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_friends_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friends',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='myapp/static/myapp/videos/', verbose_name=''),
        ),
    ]
