# Generated by Django 3.1 on 2020-10-29 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_friends_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('videofile', models.FileField(blank=True, null=True, upload_to='myapp/static/myapp/videos/', verbose_name='')),
            ],
        ),
    ]
