# Generated by Django 3.1 on 2020-10-29 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20201029_1357'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
    ]
