# Generated by Django 3.1 on 2020-10-30 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_delete_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friends',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
