# Generated by Django 3.1 on 2020-10-30 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_auto_20201030_0926'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='friends',
            options={'ordering': ('name',)},
        ),
        migrations.AlterField(
            model_name='friends',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
