# Generated by Django 3.1 on 2020-10-30 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_auto_20201030_0931'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='family',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='lovelies',
            options={'ordering': ('name',)},
        ),
    ]
