# Generated by Django 3.1 on 2020-10-30 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_auto_20201030_0932'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='family',
            options={},
        ),
        migrations.AlterModelOptions(
            name='lovelies',
            options={},
        ),
    ]
