# Generated by Django 3.1 on 2020-10-30 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_auto_20201030_0932'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='friends',
            options={},
        ),
    ]
