# Generated by Django 3.1 on 2020-10-30 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_auto_20201030_0940'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='myapp/static/myapp/images/')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='myapp/static/myapp/videos/')),
            ],
        ),
    ]
