# Generated by Django 3.1 on 2020-11-02 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_auto_20201102_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friends',
            name='message',
            field=models.TextField(max_length=5000, verbose_name=''),
        ),
    ]
