# Generated by Django 3.1 on 2020-11-02 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_auto_20201102_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='message',
            field=models.TextField(max_length=5000, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='lovelies',
            name='message',
            field=models.TextField(max_length=5000, verbose_name=''),
        ),
    ]
