# Generated by Django 3.1 on 2020-11-02 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_auto_20201102_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='message',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='friends',
            name='message',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='lovelies',
            name='message',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name=''),
        ),
    ]
