# Generated by Django 3.1 on 2020-11-02 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_auto_20201102_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='videoflag',
            field=models.BooleanField(default=False),
        ),
    ]
