# Generated by Django 3.1 on 2020-11-02 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_video_videoflag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='Pbday/myapp/static/myapp/videos/'),
        ),
    ]
