# Generated by Django 3.1 on 2020-11-02 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_auto_20201102_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='key',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
